### ISSUE TITLE
Clicking overlapping empty nodes in Terminal's Recipe Chart crashes game

### ISSUE THREAD

**Issue by robertjgreen9** [m2r1k5/nomi-ceu#490]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Added Compact Machines (compactmachines3-1.12.2-3.0.18-b278.jar) and ME Capability Adapter (capabilityadapter-1.1.3.jar) 

### Environment

Single Player and Forge Server

### Mode

Normal Mode

### What Happened

When setting up recipes in the GT Terminal's Recipe Chart, clicking nodes that overlap each other crashes the game. 

### Expected Behavior

Nothing should happen.

### Reproduction Steps

1. Created node with Add Root Slot
2. Didn't move first node
3. Created second node with Add Root Slot which overlaps first node
4. Crashes game

### Logs

[crash-2023-10-27_15.39.59-client.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/13190113/crash-2023-10-27_15.39.59-client.txt)

Web copy included from Loliasm crash screen: https://mclo.gs/tEOV6z5

### Additional Information

I also noticed the following text on the DedicatedMC Server portal when one of the crashes happen involving trying to add the crafting recipe for glass and glass panes for LV Electronic Circuit diodes. 

`[16:30:50] [Netty Epoll Server IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(15) + length(1) exceeds writerIndex(15): PooledUnsafeDirectByteBuf(ridx: 15, widx: 15, cap: 15)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:375) ~[ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:342) ~[ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) ~[ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [AbstractChannelHandlerContext.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [ByteToMessageDecoder.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [ByteToMessageDecoder.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278) [IdleStateHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) [DefaultChannelPipeline$HeadContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) [DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) [AbstractChannel$AbstractUnsafe$7.class:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [EpollEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_382]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(15) + length(1) exceeds writerIndex(15): PooledUnsafeDirectByteBuf(ridx: 15, widx: 15, cap: 15)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396) ~[AbstractByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687) ~[AbstractByteBuf.class:?]
        at net.minecraft.network.PacketBuffer.readByte(PacketBuffer.java:864) ~[gy.class:?]
        at net.minecraft.network.PacketBuffer.readVarInt(PacketBuffer.java:201) ~[gy.class:?]
        at net.minecraft.network.play.client.CPacketConfirmTeleport.readPacketData(SourceFile:21) ~[ky.class:?]
        at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40) ~[gz.class:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[ByteToMessageDecoder.class:?]
        ... 35 more
[16:30:50] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: robbygisbest lost connection: Internal Exception: io.netty.handler.codec.DecoderException: io.netty.handler.codec.EncoderException: java.io.EOFException: fieldSize is too long! Length is 2, but maximum i`

**Comment by robertjgreen9** [comment]
Turns out it also happens with the third node by itself for some reason. Fun bug woo

**Comment by IntegerLimit** [comment]
@robertjgreen9 Please add an issue in https://github.com/GregTechCEu/GregTech/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc. You can post a link to this issue, but also add a description there. (GT version 2.7.4-beta)

Please do not close this issue.

Thank you.
